### ISSUE TITLE
FATAL:   While performing build: conveyor failed to get: while converting reference: pinging container registry registry-1.docker.io: 

### ISSUE THREAD

**Issue by shafayetrahat** [apptainer/apptainer#1780]
### Version of Apptainer
`apptainer --version`
`apptainer version 1.2.4`

### Expected behavior
It should build a .def file

### Actual behavior
Fresh installation gives error while building from .def file
apptainer build --fakeroot container/fastqc.sif container/fastqc.def                                         
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while converting reference: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate has expired or is not yet valid: current time 2023-11-02T02:59:00+06:00 is after 2023-10-21T23:59:59Z

### Steps to reproduce this behavior
Followed instruction from 
[https://apptainer.org/docs/admin/main/installation.html#install-debian-packages](url)

### What OS/distro are you running

```PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer
Followed instructions from here
[https://apptainer.org/docs/admin/main/installation.html#install-debian-packages](url)
**Is it related to singularity? Or dockerhub? Or something else?**

**Comment by DrDaveD** [comment]
What's in container/fastqc.def?

**Comment by shafayetrahat** [comment]
It's just a simple definition file I am pasting it for reference
```
Bootstrap: library
From: ubuntu:latest
Stage: build
%post
    # Update and install necessary packages
    apt update -y
    apt install -y default-jre wget unzip libfindbin-libs-perl
    apt-get install -y wget locales
    locale-gen en_US.UTF-8
    update-locale LANG=en_US.UTF-8
    wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip
    unzip fastqc_v0.12.1.zip -d /opt
    chmod +x /opt/FastQC/fastqc
    ln -s /opt/FastQC/fastqc /usr/local/bin/fastqc

%environment
    export PATH=$PATH:/opt/FastQC
# You can add more sections like `%runscript`, `%test`, etc. based on your specific needs.
```

**Comment by shafayetrahat** [comment]
However, if I add the sylabs registry URL then it works. Here is my remote list
![image](https://github.com/apptainer/apptainer/assets/12217769/24f68d18-c3f7-40f6-839a-7390fa8cc00e)

**Comment by DrDaveD** [comment]
And before that you had only the default remote setting?  Because when I do that on ubuntu22.04 I get a more helpful error message:
```
FATAL:   Unable to get library client configuration: remote has no library client (see https://apptainer.org/docs/user/latest/endpoint.html#no-default-remote)
```
If you delete the SylabsCloud remote can you reproduce the problem again?

**Comment by shafayetrahat** [comment]
Sorry, my bad . The definition file was for the sylabs registry. I have corrected it. Can you check once again?

**Comment by DrDaveD** [comment]
That .def file building from docker works fine for me on Ubuntu 22.04.  It still fails for you?  That error message looks like a problem with the host certificate on the https://registry-1.docker.io server, and perhaps they have updated it.  On the other hand, if I connect to with
```
openssl s_client -connect registry-1.docker.io:443 </dev/null | openssl x509 -noout -dates
```
it shows that it was renewed in October 2023 and is valid until October 31 2024, so maybe it's a problem with the Certifying Authority certificate on your host.

**Comment by shafayetrahat** [comment]
Yes, it still fails. Maybe you are right. Any suggestion to bypass this certificate validation?

**Comment by DrDaveD** [comment]
I think you would be best off making sure the CA cert packages are up to date on your machine.  Otherwise you might try apptainer's `--no-https` option, although that's not secure.
