### ISSUE TITLE
Use unsquashfs and its library dependencies from non-standard location

### ISSUE THREAD

**Issue by phupe** [apptainer/apptainer#519]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.0.2
```

### Expected behavior

`apptainer  exec myimage.sif ls` should work.

### Actual behavior

`unsquashfs` can't find its library dependencies.
This issue is completely related to what is described here: https://github.com/apptainer/singularity/issues/5858

```
DEBUG   [U=1000,P=174492]  unsquashfsSandboxCmd()        Calling wrapped unsquashfs: apptainer [-q exec --no-home --no-nv --no-rocm -C --no-init --writable -B /tmp/rootfs-3529695249:/image -B /my/folder/bin/unsquashfs:/my/folder/bin/unsquashfs:ro -B /lib/x86_64-linux-gnu/libpthread.so.0:/lib/x86_64-linux-gnu/libpthread.so.0:ro -B /lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro -B /my/folder/bin/../lib/libz.so.1:/my/folder/lib/libz.so.1:ro -B /my/folder/bin/../lib/liblzma.so.5:/my/folder/lib/liblzma.so.5:ro -B /my/folder/bin/../lib/liblzo2.so.2:/my/folder/lib/liblzo2.so.2:ro -B /my/folder/bin/../lib/liblz4.so.1:/my/folder/lib/liblz4.so.1:ro -B /my/folder/bin/../lib/libzstd.so.1:/my/folder/lib/libzstd.so.1:ro -B /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro -B /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro -B /lib/x86_64-linux-gnu/librt.so.1:/lib/x86_64-linux-gnu/librt.so.1:ro /tmp/rootfs-3529695249/tmp-rootfs-541609790 /my/folder/bin/unsquashfs -user-xattrs -r -d /image/root /image/archive-186362059 ^(.{0}[^d]|.{1}[^e]|.{2}[^v]|.{3}[^\x2f]).*$]
DEBUG   [U=1000,P=174492]  unsquashfsSandboxCmd()
FATAL   [U=1000,P=174492]  execStarter()                 while extracting onlylinux.sif: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /my/folder/var/apptainer/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /my/folder/var/apptainer/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /my/folder/var/apptainer/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/my/folder/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
```

### Steps to reproduce this behavior

Create a conda env and install the conda package apptainer:

```
conda  create --name apptainer
conda activate apptainer
git clone https://github.com/phupe/conda-pkg-apptainer.git
cd conda-pkg-apptainer/recipe
git checkout 6b26ca8f7255e
conda build -c conda-forge .
conda install ~/miniconda3/conda-bld/linux-64/apptainer-1.0.2-h3fd9d12_1.tar.bz2
apptainer  exec myimage.sif ls
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
"Ubuntu 22.04 LTS"
```

### How did you install Apptainer

Apptainer was installed using a conda package (as described above) that I built from my repo using this version:
https://github.com/phupe/conda-pkg-apptainer/tree/6b26ca8f7255e756d69886e40084714ce4d347e2

Note that after patching the code, the issue disappears, this version works:
https://github.com/phupe/conda-pkg-apptainer/tree/c63703bfb40b713878cb9221e2187fc96917d718

**Comment by DrDaveD** [comment]
This has already been addressed in the main branch in #367.  Please try the main branch to verify if it works for you.

**Comment by phupe** [comment]
Thanks for the feedback. 

I tried to build and install my apptainer conda package using source code from the main branch using commit df2e948800bf without patching the code, but I still have the same error message: 
`/my/folder/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127`

However, I think that I understood the reason why it fails: when searching the PATH to shared libraries used by `unsquashfs`, Apptainer **does not like relative links**. Indeed, Apptainer uses `unsquashfs` found in the PATH from my conda env, and it has been installed by conda using relative links as explained [here](https://docs.conda.io/projects/conda-build/en/latest/resources/use-shared-libraries.html#shared-libraries-in-macos-and-linux). Note that my `etc/apptainer/apptainer.conf` has `# unsquashfs path =` such that `unsquashfs` is found from PATH.

If I use `unsquashfs` provided by default inside the conda anv, apptainer fails since there are relative links to the shared libraries:

```
$ ldd /my/folder/bin/unsquashfs
	linux-vdso.so.1 (0x00007ffc59477000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8af23e1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8af22fa000)
	libz.so.1 => /my/folder/bin/../lib/libz.so.1 (0x00007f8af22e0000)
	liblzma.so.5 => /my/folder/bin/../lib/liblzma.so.5 (0x00007f8af22b7000)
	liblzo2.so.2 => /my/folder/bin/../lib/liblzo2.so.2 (0x00007f8af2272000)
	liblz4.so.1 => /my/folder/bin/../lib/liblz4.so.1 (0x00007f8af223c000)
	libzstd.so.1 => /my/folder/bin/../lib/libzstd.so.1 (0x00007f8af2178000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8af1f50000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8af25a1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8af1f4b000)
```

While if i use `unsquashfs` (installed in `/opt/mysquashfs/bin/`) that I have recompiled from source and linked to `/my/folder/lib` to use the exact same shared libraries as above but without the relative links, it works (after `export PATH=/opt/mysquashfs/bin/:$PATH`:

```
$ ldd /opt/mysquashfs/bin/unsquashfs
	linux-vdso.so.1 (0x00007ffcbbf8b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f828d070000)
	libz.so.1 => /my/folder/lib/libz.so.1 (0x00007f828d056000)
	liblzma.so.5 => /my/folder/lib/liblzma.so.5 (0x00007f828d02d000)
	liblzo2.so.2 => /my/folder/lib/liblzo2.so.2 (0x00007f828cfe8000)
	liblz4.so.1 => /my/folder/lib/liblz4.so.1 (0x00007f828cfb4000)
	libzstd.so.1 => /my/folder/lib/libzstd.so.1 (0x00007f828ceee000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f828ccc6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f828d327000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f828ccc1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f828ccbc000)
```

Anyway, I think this might be trivial to fix the relative link issue but have no idea how to do it.

**Comment by phupe** [comment]
It seems that the issue is due to the binding `-B` option which contains relative path when apptainer starts.

Indeed, `apptainer -d exec myimage.sif ls` says:

```
 /tmp/rootfs-882200450:/image -B /my/folder/bin/unsquashfs:/my/folder/bin/unsquashfs:ro 
-B /lib/x86_64-linux-gnu/libpthread.so.0:/lib/x86_64-linux-gnu/libpthread.so.0:ro 
-B /lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro 
-B /my/folder/bin/../lib/libz.so.1:/my/folder/lib/libz.so.1:ro 
-B /my/folder/bin/../lib/liblzma.so.5:/my/folder/lib/liblzma.so.5:ro 
-B /my/folder/bin/../lib/liblzo2.so.2:/my/folder/lib/liblzo2.so.2:ro 
-B /my/folder/bin/../lib/liblz4.so.1:/my/folder/lib/liblz4.so.1:ro 
-B /my/folder/bin/../lib/libzstd.so.1:/my/folder/lib/libzstd.so.1:ro 
-B /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro 
-B /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro 
-B /lib/x86_64-linux-gnu/librt.so.1:/lib/x86_64-linux-gnu/librt.so.1:ro /tmp/rootfs-882200450/tmp-rootfs-1239700871 /my/folder/bin/unsquashfs -user-xattrs -r -d /image/root /image/archive-3136463503 ^(.{0}[^d]|.{1}[^e]|.{2}[^v]|.{3}[^\x2f]).*$]
DEBUG   [U=1000,P=602046]  unsquashfsSandboxCmd()        
LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/my/folder/lib:/lib64
```
We clearly see the `../lib/`.
I also printed LD_LIBRARY_PATH which is correctly set. 
The following code says `// The binary path must be absolute.`:

https://github.com/apptainer/apptainer/blob/5074370e664f7fed5bc7f676a228b1fe1e564343/internal/pkg/image/unpacker/squashfs_apptainer.go#L44-L46

I guess the patch would consist to add `filepath.Abs()` somewhere in the function `getLibraryBinds` in the file 
https://github.com/apptainer/apptainer/blob/5074370e664f7fed5bc7f676a228b1fe1e564343/internal/pkg/image/unpacker/squashfs_apptainer.go. I take a look.

**Comment by phupe** [comment]
I this patch to remove `../` in the path passed to -B option, but the errror is still there.
 
```
diff --git a/internal/pkg/image/unpacker/squashfs_apptainer.go b/internal/pkg/image/unpacker/squashfs_apptainer.go
index 07808a9fc..7eb8f7b0a 100644
--- a/internal/pkg/image/unpacker/squashfs_apptainer.go
+++ b/internal/pkg/image/unpacker/squashfs_apptainer.go
@@ -130,7 +130,7 @@ func parseLibraryBinds(buf io.Reader) ([]libBind, error) {
                        destDir := filepath.Dir(fields[2])
                        dest := filepath.Join(destDir, fields[0])
                        libs = append(libs, libBind{
-                               source: fields[2],
+                               source: filepath.Clean(fields[2]),
                                dest:   dest,
                        })
                }


```
`
apptainer -d exec myimage.sif ls` says:

```
DEBUG   [U=1000,P=701532]  unsquashfsSandboxCmd()        Calling wrapped unsquashfs: apptainer [-q exec --no-home --no-nv --no-rocm -C --no-init --writable -B /tmp/rootfs-2814102625:/image 
-B /my/folder/bin/unsquashfs:/my/folder/bin/unsquashfs:ro 
-B /lib/x86_64-linux-gnu/libpthread.so.0:/lib/x86_64-linux-gnu/libpthread.so.0:ro 
-B /lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro 
-B /my/folder/lib/libz.so.1:/my/folder/lib/libz.so.1:ro 
-B /my/folder/lib/liblzma.so.5:/my/folder/lib/liblzma.so.5:ro 
-B /my/folder/lib/liblzo2.so.2:/my/folder/lib/liblzo2.so.2:ro 
-B /my/folder/lib/liblz4.so.1:/my/folder/lib/liblz4.so.1:ro 
-B /my/folder/lib/libzstd.so.1:/my/folder/lib/libzstd.so.1:ro 
-B /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro 
-B /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro 
-B /lib/x86_64-linux-gnu/librt.so.1:/lib/x86_64-linux-gnu/librt.so.1:ro /tmp/rootfs-2814102625/tmp-rootfs-4078966984 /my/folder/bin/unsquashfs -user-xattrs -r -d /image/root /image/archive-4190092983 ^(.{0}[^d]|.{1}[^e]|.{2}[^v]|.{3}[^\x2f]).*$]

/my/folder/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

So far the only patch that fixes the issue is the one provide in https://github.com/apptainer/apptainer/pull/520.

**Comment by phupe** [comment]
I provide here some information about the RPATH for `unsquashfs`:

```
readelf -d /my/folder/bin/unsquashfs
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib]
```

After patching the RPATH with the absolute path to the shared library folder, apptainer just work fine:
```
patchelf --set-rpath  /my/folder/lib  /my/folder/bin/unsquashfs
readelf -d /my/folder/bin/unsquashfs
 0x000000000000001d (RUNPATH)            Library runpath: [/my/folder/lib]
```

**Comment by DrDaveD** [comment]
I'm not sure what's happening with those relative paths, but the main branch will search through the user's path if running in non-suid mode.  Does it work if you run in non-suid mode?  Otherwise in suid mode you would need to add the directory to the `binary path` option in `/etc/apptainer/apptainer.conf`.   I don't think #520 is secure for suid mode.

**Comment by phupe** [comment]
Thanks. I understand the security issue.

Apptainer is compiled that way:

```
./mconfig \
  -P release-stripped \
  --without-suid
``` 

`etc/apptainer/apptainer.conf` contains `allow setuid = yes`. I also tried to set in the config file the following:

```
binary path = /my/folder/bin
unsquashfs path = /my/folder/bin/unsquashfs
```

I also tried to patch the code to add these binding options `-B /my/folder/bin:/my/folder/bin:ro -B /my/folder/lib:/my/folder/lib:ro` for `unsquashfsSandboxCmd`.

The is no way to make it work.

At the end the recommendation is just to remove `patchelf --set-rpath  /my/folder/lib  /my/folder/bin/unsquashfs`.

**Comment by DrDaveD** [comment]
> At the end the recommendation is just to remove patchelf --set-rpath /my/folder/lib /my/folder/bin/unsquashfs

Ok so does that mean there's no change needed to apptainer and the issue can be closed?

**Comment by phupe** [comment]
Indeed, I think we can close as I found a workaround and it doesn't seem that there is a straightforward solution.
Thanks.
